# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

---
- block:
  - name: copy log_collector to the controller
    copy:
      src: ./scripts/log_collector{{ item.ext }}
      dest: "{{ ansible_facts.user_dir }}/log_collector{{ item.ext }}"
      mode: "{{ item.mode }}"
    loop:
    - {ext: "", mode: "a=rx,u+w"}
    - {ext: ".py", mode: "a=rx,u+w"}
    - {ext: ".json", mode: "a=r,u+w"}

  - name: collect logs
    command: "{{ ansible_facts.user_dir }}/log_collector.py --output-file Result.tar.gz --force"
    args:
      chdir: "{{ ansible_facts.user_dir }}"
    become: yes
    changed_when: true

  - name: create var for filename
    set_fact:
      log_filename: ./failed_readiness_logs_{{ ansible_date_time.iso8601_basic_short }}.tar.gz

  - name: get logs from remote
    fetch:
      src: "{{ ansible_facts.user_dir }}/Result.tar.gz"
      dest: "{{ log_filename }}"
      flat: true

  delegate_to: "{{ groups['controller_group'][0] }}"
  run_once: true
