# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2022 Intel Corporation
---
- block:
  - name: create dest directory on node
    file:
      path: "{{ CNI_plugins.dest | dirname }}/CNI_plugins"
      owner: "{{ CNI_plugins.owner }}"
      mode: a=rx,u+w
      state: directory
      recurse: yes
    become: yes

  - name: download item
    get_url:
      url: "{{ CNI_plugins.url }}"
      dest: "{{ CNI_plugins.dest }}"
      owner: "{{ CNI_plugins.owner }}"
      mode: "{{ CNI_plugins.mode }}"
    delegate_to: "{{ inventory_hostname }}"
    register: get_url_result
    until: "'OK' in get_url_result.msg or 'file already exists' in get_url_result.msg"
    retries: 4
    delay: 5
    no_log: false
    become: yes

  - name: unpack archive
    unarchive:
      src: "{{ CNI_plugins.dest }}"
      dest: "{{ CNI_plugins.dest | dirname }}/CNI_plugins"
      owner: "{{ CNI_plugins.owner }}"
      mode: "{{ CNI_plugins.mode }}"
      copy: no
    become: yes

  - name: create CNI directory on node
    file:
      path: "/opt/cni/bin/"
      owner: "{{ CNI_plugins.owner }}"
      mode: a=rx,u+w
      state: directory
      recurse: yes
    become: yes

  - name: copy CNI_plugins binary from download dir
    copy:
      remote_src: yes
      src: "{{ local_release_dir }}/CNI_plugins/{{ item }}"
      dest: "/opt/cni/bin"
      mode: a=rx,u+w
    loop:
      - bandwidth  
      - bridge  
      - dhcp  
      - firewall  
      - host-device  
      - host-local  
      - ipvlan  
      - loopback  
      - macvlan  
      - portmap  
      - ptp  
      - sbr  
      - static  
      - tuning  
      - vlan  
      - vrf
    become: yes
