# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2020 Intel Corporation

---
_calico_version: "v3.24.0"
_calico_manifest: "{{ 'calico-bpf.yaml' if ( calico_ebpf_enabled | default(false) ) else 'calico.yaml' }}"
_calico_url: https://raw.githubusercontent.com/projectcalico/calico/{{ _calico_version }}/manifests/{{ _calico_manifest }}
calico_ipam_type: "{{ 'calico-ipam' if ( calico_ebpf_enabled | default(false) ) else 'host-local' }}"

calico_cidr: "10.245.0.0/16"
