# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2021-2022 Intel Corporation

---
# Variable that should be set for this role:
# - proxy_env:
#     http_proxy: str
#     https_proxy: str
#     ftp_proxy: str
#     no_proxy: str

- name: configure /etc/environment proxy settings
  block:
    - name: set lowercase proxy settings
      lineinfile:
        path: /etc/environment
        state: "{{ 'present' if item.value | length > 0 else 'absent' }}"
        regexp: '^{{ item.key }}'
        line: "{{ item.key }}={{ item.value }}"
        create: true
        owner: root
        group: root
        mode: a=r,u+w
      loop: "{{ proxy_env | default({}) | dict2items }}"
  
    - name: set uppercase proxy settings
      lineinfile:
        path: /etc/environment
        state: "{{ 'present' if item.value | length > 0 else 'absent' }}"
        regexp: '^{{ item.key | upper }}'
        line: "{{ item.key | upper }}={{ item.value }}"
        create: true
        owner: root
        group: root
        mode: a=r,u+w
      loop: "{{ proxy_env | default({}) | dict2items }}"
  become: yes
  when: >
    "http_proxy" in proxy_env or
    "https_proxy" in proxy_env or
    "ftp_proxy" in proxy_env
